[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]
excludes = [".devenv.flake.nix"]
priority = 3

[formatter.deadnix]
command = "deadnix"
options = ["--edit"]
includes = ["*.nix"]
priority = 2

[formatter.statix]
command = "statix"
options = ["fix", "-i", ".direnv"]
includes = ["*.nix"]
priority = 1

[formatter.toml]
command = "taplo"
options = ["fmt"]
includes = ["*.toml"]
