name: ci

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Install devenv
        run: nix profile install nixpkgs#devenv
      - name: Update manifest version
        if: ${{ github.ref_type == 'tag' }}
        uses: cssnr/update-json-value-action@v1
      - name: Install
        run: devenv tasks run ext:install
      - name: Build
        run: devenv tasks run ext:build
      - name: Zip
        run: devenv tasks run ext:zip
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bookup-${{ github.sha }}
          path: .output/*.zip
          retention-days: 7
          overwrite: true
      - name: Release
        if: ${{ github.ref_type == 'tag' }}
        uses: ghalactic/github-release-from-tag@v5
        with:
          assets: |
            - path: ".output/*.zip"
          summaryEnabled: "false"
