name: ci

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv
        run: nix profile install nixpkgs#devenv
      - name: Update manifest version
        if: ${{ github.ref_type == 'tag' }}
        uses: cssnr/update-json-value-action@v1
      - name: Build
        run: devenv tasks run ext:build
      - name: Lint
        run: devenv tasks run ext:lint
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bookup-${{ github.sha }}
          path: artifacts/*.zip
          retention-days: 7
          overwrite: true
      - name: Release
        if: ${{ github.ref_type == 'tag' }}
        uses: ghalactic/github-release-from-tag@v5
        with:
          assets: |
            - path: "artifacts/*.zip"
          summaryEnabled: "false"
