name: cleanup
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      reference:
        description: 'The reference to clean up caches for (e.g., refs/heads/branch-name, refs/tags/tag-name, refs/pull/PR-number/merge)'
        required: true
        default: ''

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Determine reference
        id: determine-reference
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            REFERENCE="${{ github.event.inputs.reference }}"
          else
            REFERENCE="refs/pull/${{ github.event.pull_request.number }}/merge"
          fi
          echo "reference=$REFERENCE" >> "$GITHUB_OUTPUT"
      - name: Clean caches
        id: clean-caches
        run: |
          set +e
          totalDeleted=0

          echo "Deleting caches for reference $REFERENCE"
          while true; do
            cacheKeys=$(gh cache list --ref "$REFERENCE" --limit 100 --json id --jq '.[].id')
            numCacheKeys=$(echo "$cacheKeys" | wc -w)

            if [[ "$numCacheKeys" -eq 0 ]]; then
              echo "No more caches to delete"
              break
            fi

            echo "Deleting $numCacheKeys caches..."
            for cacheKey in $cacheKeys
            do
              gh cache delete "$cacheKey"
              totalDeleted=$((totalDeleted + 1))
            done
          done

          echo "Deleted $totalDeleted caches in total"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          REFERENCE: ${{ steps.determine-reference.outputs.reference }}
